name: Ubuntu RDP

on: 
  workflow_dispatch:
  
    inputs:
      authcode:
        description: 'Visit http://remotedesktop.google.com/headless and copy the command after Authentication'
        required: true
      pincode:
        description: 'Enter a Pin (more or equal to 6 digits)'
        default: '123456'
        required: true
      authtoken:
        description: 'NGROK AUTH TOKEN'
        required: false
      computername:
        description: 'MACHINE NAME'
        default: 'ubuntu'
        required: true
      username:
        description: 'USER NAME'
        default: 'user'
        required: true
      password:
        description: 'USER PASSWORD'
        default: 'root'
        required: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2

    - name: Mask Code & Pin.
      run: |
        _Token=$(jq -r '.inputs.authtoken' $GITHUB_EVENT_PATH)
        _CName=$(jq -r '.inputs.computername' $GITHUB_EVENT_PATH)
        _Pass=$(jq -r '.inputs.password' $GITHUB_EVENT_PATH)
        echo ::add-mask::$_Token
        echo ::add-mask::$_CName
        echo ::add-mask::$_Pass
        echo NGROK_TOKEN="$_Token" >> $GITHUB_ENV
        echo ComputerName="$_CName" >> $GITHUB_ENV
        echo Password="$_Pass" >> $GITHUB_ENV

    - name: Initializing Installation
      run: |
           sudo apt update 
           sudo apt upgrade

    - name: Installing Chrome Remote Desktop
      run: |
           wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
           sudo apt-get install --assume-yes ./chrome-remote-desktop_current_amd64.deb

    - name: Installing Ubuntu Desktop Environment (wait for 10 min)
      run: sudo apt install ubuntu-desktop

    - name: Installing Some Configurations
      run: |
           sudo apt install nautilus expect nano -y
           sudo apt install --assume-yes xscreensaver

    - name: Installing Xbase Clients
      run: sudo apt-get install xbase-clients python3-psutil xvfb -y

    - name: Setting up Environment
      run: |
           bash Setup.sh "${{ env.NGROK_TOKEN }}" "${{ env.ComputerName }}" "${{ github.event.inputs.username }}" "${{ env.Password }}"
    
    - name: IP for Connecting to SSH
      run: bash Ip.sh "${{ github.event.inputs.username }}"
    
    - name: Start Chrome Remote Desktop
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}

    - name: Keep Alive
      run: ping 127.0.0.1 > null
